<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2019 广东卓锐软件有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => 'AI绘画',
    'icon' => 'fa fa-fw fa-paint-brush',
    'url_type' => 'module_admin',
    'url_value' => 'drawing/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '小说工具',
        'icon' => 'fa fa-fw fa-book',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 0,
        'status' => 1,
        'child' => [
          [
            'title' => '用户',
            'icon' => 'fa fa-fw fa-address-book',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/mac_user/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '激活码',
            'icon' => 'fa fa-fw fa-folder',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/activate_code/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '添加7天码',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add7daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '添加月卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add31daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '添加年卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add365daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '添加永久',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/addforevercode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '日卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add1daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '季卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add93daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '3天卡',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/add3daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '导出激活码',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/activate_code/download',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '时长码',
            'icon' => 'fa fa-fw fa-graduation-cap',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/duration_code/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '添加时长1',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add7daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '新增时长2',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add31daycode',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '48',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add48hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '24',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add24hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '12',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add12hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '1小时',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add1hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '2hour',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add2hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '4hour',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/duration_code/add4hour',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '绘画状态',
            'icon' => 'fa fa-fw fa-eye',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/video_progress/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
          ],
          [
            'title' => '机器表',
            'icon' => 'fa fa-fw fa-usd',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/sdyun_url/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/sdyun_url/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/sdyun_url/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '访问记录',
            'icon' => 'fa fa-fw fa-address-card-o',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/mac_sdyun_cnt/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => '绘画列表',
            'icon' => 'fa fa-fw fa-magic',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/midjourney_task/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => 'MJ账号管理',
            'icon' => 'fa fa-fw fa-trademark',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/midjourney_info/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/midjourney_info/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => 'Azure语音服务',
            'icon' => 'fa fa-fw fa-space-shuttle',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/azure_speech/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/azure_speech/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/azure_speech/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/azure_speech/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '更新秘钥状态',
                'icon' => 'fa fa-fw fa-refresh',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/azure_speech/update_key',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '速推日报',
            'icon' => 'fa fa-fw fa-birthday-cake',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/day_sutui_data/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
          [
            'title' => 'gpt_key列表',
            'icon' => 'fa fa-fw fa-key',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/gpt_key/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 200,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/gpt_key/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/gpt_key/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '更新',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/gpt_key/updatetoken',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'lora模型列表',
        'icon' => 'fa fa-fw fa-align-left',
        'url_type' => 'module_admin',
        'url_value' => 'drawing/lora_list/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 0,
        'child' => [
          [
            'title' => '新增',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/lora_list/add',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '编辑',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/lora_list/edit',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '首页',
        'icon' => 'fa fa-fw fa-window-maximize',
        'url_type' => 'module_admin',
        'url_value' => 'drawing/index/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '获取用户数',
            'icon' => '',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/index/getuserdata',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '数据报表',
        'icon' => 'fa fa-fw fa-upload',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 1,
        'child' => [
          [
            'title' => '充值订单列表',
            'icon' => 'fa fa-fw fa-cc-paypal',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/order_info/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '任务领取记录',
            'icon' => 'fa fa-fw fa-cubes',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/user_task_coin/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '点券消耗信息',
            'icon' => 'fa fa-fw fa-thermometer-half',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/wallet_info/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/wallet_info/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '用户日报数据',
            'icon' => 'fa fa-fw fa-calendar-o',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/day_user_data/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '小程序配置',
        'icon' => 'fa fa-fw fa-scissors',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 1,
        'child' => [
          [
            'title' => '任务配置',
            'icon' => 'fa fa-fw fa-cogs',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/task_info/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/task_info/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/task_info/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '充值配置',
            'icon' => 'fa fa-fw fa-shopping-cart',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/shop_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/shop_list/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/shop_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '订阅管理',
            'icon' => 'fa fa-fw fa-square-o',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/wx_template/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/wx_template/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/wx_template/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '推送列表',
            'icon' => 'fa fa-fw fa-comments',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/wx_subscribe/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
          ],
          [
            'title' => '资讯配置',
            'icon' => 'fa fa-fw fa-newspaper-o',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/information_details/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 5,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/information_details/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/information_details/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '活动配置',
            'icon' => 'fa fa-fw fa-indent',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/information_index/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 6,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/information_index/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/information_index/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '查看链接',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/information_index/ads_url',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '首页轮播图配置',
            'icon' => 'fa fa-fw fa-bank',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/banner/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 7,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/banner/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/banner/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '系统参数配置',
            'icon' => 'fa fa-fw fa-cog',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/app_config/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 8,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '用户信息',
        'icon' => 'fa fa-fw fa-user',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 5,
        'status' => 1,
        'child' => [
          [
            'title' => '用户信息',
            'icon' => 'fa fa-fw fa-user-circle',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/user_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/user_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '模型管理',
        'icon' => 'fa fa-fw fa-camera',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 6,
        'status' => 1,
        'child' => [
          [
            'title' => '模型列表',
            'icon' => 'fa fa-fw fa-align-center',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/big_models_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/big_models_list/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/big_models_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '风格管理',
            'icon' => 'fa fa-fw fa-align-justify',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/style_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/style_list/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/style_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '推荐词',
            'icon' => 'fa fa-fw fa-list',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/prompt_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/prompt_list/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/prompt_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '词分类',
            'icon' => 'fa fa-fw fa-certificate',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/tags_cat/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 4,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/tags_cat/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/tags_cat/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '词标签',
            'icon' => 'fa fa-fw fa-connectdevelop',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/tags_content/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 5,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/tags_content/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/tags_content/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '古诗词配置',
            'icon' => 'fa fa-fw fa-book',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/poetry_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 6,
            'status' => 1,
            'child' => [
              [
                'title' => '增加',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/poetry_list/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/poetry_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '单风格活动配置',
            'icon' => 'fa fa-fw fa-image',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/single_style/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 7,
            'status' => 0,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/single_style/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/single_style/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '绘图管理',
        'icon' => 'fa fa-fw fa-file-picture-o',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 7,
        'status' => 1,
        'child' => [
          [
            'title' => '作品',
            'icon' => 'fa fa-fw fa-align-right',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/draw_img_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/draw_img_list/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '绘图任务',
            'icon' => 'fa fa-fw fa-fighter-jet',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/draw_task_list/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '视频任务',
            'icon' => 'fa fa-fw fa-video-camera',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/video_task/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/video_task/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/video_task/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '绘画机器列表',
            'icon' => 'fa fa-fw fa-american-sign-language-interpreting',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/draw_host/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 5,
            'status' => 1,
          ],
          [
            'title' => '文本生成视频',
            'icon' => 'fa fa-fw fa-video-camera',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/text_to_video/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 6,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/text_to_video/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/text_to_video/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '拆词详情',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/text_to_detail/index',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
                'child' => [
                  [
                    'title' => '编辑',
                    'icon' => '',
                    'url_type' => 'module_admin',
                    'url_value' => 'drawing/text_to_detail/edit',
                    'url_target' => '_self',
                    'online_hide' => 0,
                    'sort' => 1,
                    'status' => 1,
                  ],
                ],
              ],
            ],
          ],
          [
            'title' => '换脸视频制作',
            'icon' => 'fa fa-fw fa-facebook-f',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/face_swap/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 7,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/face_swap/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/face_swap/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '黑岩故事',
        'icon' => 'fa fa-fw fa-book',
        'url_type' => 'module_admin',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 8,
        'status' => 1,
        'child' => [
          [
            'title' => '书本',
            'icon' => 'fa fa-fw fa-align-left',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/hybook/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '章节',
            'icon' => 'fa fa-fw fa-save',
            'url_type' => 'module_admin',
            'url_value' => 'drawing/hybook_info/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'drawing/hybook_info/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
